name: 'Run Android'
description: 'Run a remote Android instance in Limbar'
author: 'Limbar, Inc.'

inputs:
  organization-id:
    description:
      'Organization that the Android instance will belong to. If not given, the
      default organization from the token is used.'
    required: false
  region:
    description:
      'Region of the Android instance. The closest one is chosen if not given.'
    required: false
  token:
    description: 'Token to access Limbar.'
    required: true

runs:
  using: node20
  main: dist/index.js
  post: dist/cleanup.js
