name: 'Android Emulator Fleet'
description:
  'Run as many Android emulators as your automated app tests need in parallel.'
author: 'Limbar, Inc.'
branding:
  icon: smartphone
  color: blue

inputs:
  organization-id:
    description:
      'Organization that the Android instance will belong to. If not given, the
      default organization from the token is used.'
    required: false
  region:
    description:
      'Region of the Android instance. The closest one is chosen if not given.'
    required: false
  token:
    description: 'Token to access Limbar.'
    required: true
  count:
    description: 'Number of Android instances to run.'
    required: false
    default: '1'

runs:
  using: node20
  main: dist/index.js
  post: dist/cleanup/index.js
